name: bigdata
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy<2
  - pandas>=2.0
  - scipy>=1.10
  - yfinance>=0.2
  - coverage>=7.10
  - pytest>=8.0
  - pytest-cov>=7.0
  - jupyterlab>=4.0
  - pip:
      - -e ".[test]"
